/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import DAO.SerieDAO;
import java.util.List;
import javaBeans.Serie;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonardo
 */
public class TelaCadastroSeries extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFilme
     */
    
    // listar
    public void listar(){
        try {
            // executando o select
        SerieDAO dao = new SerieDAO();
        List<Serie> listSerie = dao.listaSeries();
        
        // colocando os dados na tabela
        DefaultTableModel model = (DefaultTableModel) tabelaSeries.getModel();
        model.setRowCount(0);
        
        for(Serie s : listSerie){
            model.addRow(new Object[]{
               s.getIdSerie(),
               s.getNome(),
               s.getGenero(),
               s.getDirecao(),
               s.getAnoLancamento(),
               s.getTemporadas(),
               s.getStreamer(),
               s.getAssistiu()
            });
        }
            
        
        } catch (Exception e) {
        }
    }
    
    public TelaCadastroSeries() {
        super("Tela de cadastro");
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(950, 600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        generoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anoLancamentoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        direcaoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        streamerTextField = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSeries = new javax.swing.JTable();
        botaoDeletar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        botaoAtencao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        temporadaTextField = new javax.swing.JTextField();
        assistiuCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Séries");

        jLabel2.setText("Nome: ");

        jLabel3.setText("Genero: ");

        jLabel4.setText("Ano lançamento: ");

        jLabel5.setText("Direção: ");

        jLabel6.setText("Streamer:");

        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.setContentAreaFilled(false);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(0, 153, 51));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoAlterar.setBackground(new java.awt.Color(51, 102, 255));
        botaoAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        tabelaSeries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Serie", "Nome", "Genero", "Direção", "Ano Lançamento", "Temporadas", "Streamer", "Assistiu"
            }
        ));
        tabelaSeries.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tabelaSeries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSeriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSeries);

        botaoDeletar.setBackground(new java.awt.Color(255, 51, 51));
        botaoDeletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoDeletar.setForeground(new java.awt.Color(255, 255, 255));
        botaoDeletar.setText("Deletar");
        botaoDeletar.setBorderPainted(false);
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        jLabel7.setText("ID: ");

        botaoLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.setContentAreaFilled(false);
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoAtencao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botaoAtencao.setForeground(new java.awt.Color(51, 102, 255));
        botaoAtencao.setText("?");
        botaoAtencao.setContentAreaFilled(false);
        botaoAtencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtencaoActionPerformed(evt);
            }
        });

        jLabel8.setText("Temporadas: ");

        assistiuCheck.setText("Já assistiu ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCadastrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTextField)
                            .addComponent(streamerTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(temporadaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(generoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(direcaoTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(anoLancamentoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(idTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoAtencao)
                                    .addComponent(assistiuCheck))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(anoLancamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistiuCheck)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(generoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAtencao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(direcaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temporadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(streamerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(botaoCadastrar)
                    .addComponent(botaoAlterar)
                    .addComponent(botaoDeletar)
                    .addComponent(botaoLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        JFrame frame = new TelaSeries();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        
        try {
            Serie obj = new Serie();
            obj.setNome(nomeTextField.getText());
            obj.setGenero(generoTextField.getText());
            obj.setDirecao(direcaoTextField.getText());
            obj.setAnoLancamento(Integer.parseInt(anoLancamentoTextField.getText()));
            obj.setTemporadas(temporadaTextField.getText());
            obj.setStreamer(streamerTextField.getText());
            
            if(assistiuCheck.isSelected()){
                obj.setAssistiu("Sim");
            } else {
                obj.setAssistiu("Não");
            }
            
            SerieDAO dao = new SerieDAO();
            dao.cadastraSerie(obj);
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!!!");
            
        } catch (Exception erroSql) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + erroSql);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void tabelaSeriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSeriesMouseClicked
        idTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 0).toString());
        nomeTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 1).toString());
        generoTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 2).toString());
        direcaoTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 3).toString());
        anoLancamentoTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 4).toString());
        temporadaTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 5).toString());
        streamerTextField.setText(tabelaSeries.getValueAt(tabelaSeries.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tabelaSeriesMouseClicked

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        idTextField.setText("");
        nomeTextField.setText("");
        generoTextField.setText("");
        direcaoTextField.setText("");
        anoLancamentoTextField.setText("");
        temporadaTextField.setText("");
        streamerTextField.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        
        try {
            Serie obj = new Serie();
            obj.setIdSerie(Integer.parseInt(idTextField.getText()));
            
            SerieDAO dao = new SerieDAO();
            dao.deletaSerie(obj);
            
            JOptionPane.showMessageDialog(null, "Serie deletado com sucesso!!!");
            
        } catch (Exception erroSql) {
            JOptionPane.showMessageDialog(null, "Erro ao deletar: " + erroSql);
        }
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        
        try {
            Serie obj = new Serie();
            obj.setIdSerie(Integer.parseInt(idTextField.getText()));
            obj.setNome(nomeTextField.getText());
            obj.setGenero(generoTextField.getText());
            obj.setDirecao(direcaoTextField.getText());
            obj.setAnoLancamento(Integer.parseInt(anoLancamentoTextField.getText()));
            obj.setTemporadas(temporadaTextField.getText());
            obj.setStreamer(streamerTextField.getText());
            
            if(assistiuCheck.isSelected()){
                obj.setAssistiu("Sim");
            } else {
                obj.setAssistiu("Não");
            }
            
            SerieDAO dao = new SerieDAO();
            dao.alterarSerie(obj);
            
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!!!");
        } catch (Exception erroSql) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar !!!" + erroSql);
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoAtencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtencaoActionPerformed
        
        JOptionPane.showMessageDialog(null, "Para cadastrar não é necessário prencher o campo 'ID'.");
    }//GEN-LAST:event_botaoAtencaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroSeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroSeries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoLancamentoTextField;
    private javax.swing.JCheckBox assistiuCheck;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoAtencao;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JTextField direcaoTextField;
    private javax.swing.JTextField generoTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField streamerTextField;
    private javax.swing.JTable tabelaSeries;
    private javax.swing.JTextField temporadaTextField;
    // End of variables declaration//GEN-END:variables
}
